(function(){var aa=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}},g="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a},ba=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");
},h=ba(this),k=function(a,b){if(b)a:{var c=h;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))break a;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&g(c,a,{configurable:!0,writable:!0,value:b})}};
k("Symbol",function(a){if(a)return a;var b=function(f,p){this.g=f;g(this,"description",{configurable:!0,writable:!0,value:p})};b.prototype.toString=function(){return this.g};var c="jscomp_symbol_"+(1E9*Math.random()>>>0)+"_",d=0,e=function(f){if(this instanceof e)throw new TypeError("Symbol is not a constructor");return new b(c+(f||"")+"_"+d++,f)};return e});
k("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<b.length;c++){var d=h[b[c]];"function"===typeof d&&"function"!=typeof d.prototype[a]&&g(d.prototype,a,{configurable:!0,writable:!0,value:function(){return ca(aa(this))}})}return a});
var ca=function(a){a={next:a};a[Symbol.iterator]=function(){return this};return a},l=function(a){return a.raw=a},m=function(a,b){a.raw=b;return a},da=function(){for(var a=Number(this),b=[],c=a;c<arguments.length;c++)b[c-a]=arguments[c];return b},ea=function(a,b){a instanceof String&&(a+="");var c=0,d=!1,e={next:function(){if(!d&&c<a.length){var f=c++;return{value:b(f,a[f]),done:!1}}d=!0;return{done:!0,value:void 0}}};e[Symbol.iterator]=function(){return e};return e};
k("Array.prototype.entries",function(a){return a?a:function(){return ea(this,function(b,c){return[b,c]})}});/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var n=this||self,q=function(a,b){function c(){}c.prototype=b.prototype;a.o=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.m=function(d,e,f){for(var p=Array(arguments.length-2),r=2;r<arguments.length;r++)p[r-2]=arguments[r];return b.prototype[e].apply(d,p)}},t=function(a){return a};function u(a,b){if(Error.captureStackTrace)Error.captureStackTrace(this,u);else{var c=Error().stack;c&&(this.stack=c)}a&&(this.message=String(a));void 0!==b&&(this.cause=b)}q(u,Error);u.prototype.name="CustomError";function v(a,b){a=a.split("%s");for(var c="",d=a.length-1,e=0;e<d;e++)c+=a[e]+(e<b.length?b[e]:"%s");u.call(this,c+a[d])}q(v,u);v.prototype.name="AssertionError";var w=function(a,b){throw new v("Failure"+(a?": "+a:""),Array.prototype.slice.call(arguments,1));};var x;var z=function(a,b){if(b!==y)throw Error("TrustedResourceUrl is not meant to be built directly");this.g=a};z.prototype.toString=function(){return this.g+""};var y={},A=function(a){if(void 0===x){var b=null;var c=n.trustedTypes;if(c&&c.createPolicy){try{b=c.createPolicy("goog#html",{createHTML:t,createScript:t,createScriptURL:t})}catch(d){n.console&&n.console.error(d.message)}x=b}else x=b}a=(b=x)?b.createScriptURL(a):a;return new z(a,y)};var C=function(a){if(B!==B)throw Error("SafeUrl is not meant to be built directly");this.g=a};C.prototype.toString=function(){return this.g.toString()};var B={};new C("about:invalid#zClosurez");new C("about:blank");var D={},E=function(){if(D!==D)throw Error("SafeStyle is not meant to be built directly");};E.prototype.toString=function(){return"".toString()};new E;var F={},G=function(){if(F!==F)throw Error("SafeStyleSheet is not meant to be built directly");};G.prototype.toString=function(){return"".toString()};new G;var H={},I=function(){var a=n.trustedTypes&&n.trustedTypes.emptyHTML||"";if(H!==H)throw Error("SafeHtml is not meant to be built directly");this.g=a};I.prototype.toString=function(){return this.g.toString()};new I;var J=function(a,b){this.name=a;this.value=b};J.prototype.toString=function(){return this.name};
var K=new J("OFF",Infinity),L=new J("WARNING",900),fa=new J("CONFIG",700),ha=function(){},M,ia=function(){},N=function(a,b){this.g=null;this.j=[];this.h=(void 0===b?null:b)||null;this.i=[];this.l={g:function(){return a}}},ja=function(a){if(a.g)return a.g;if(a.h)return ja(a.h);w("Root logger has no level set.");return K},ka=function(a){for(var b=new ia;a;)a.j.forEach(function(c){c(b)}),a=a.h},la=function(){this.entries={};var a=new N("");a.g=fa;this.entries[""]=a},O,P=function(a,b){var c=a.entries[b];
if(c)return c;c=P(a,b.slice(0,Math.max(b.lastIndexOf("."),0)));var d=new N(b,c);a.entries[b]=d;c.i.push(d);return d},Q=function(){O||(O=new la);return O};/*

 SPDX-License-Identifier: Apache-2.0
*/
var ma=l([""]),na=m(["\x00"],["\\0"]),oa=m(["\n"],["\\n"]),pa=m(["\x00"],["\\u0000"]),qa=l([""]),ra=m(["\x00"],["\\0"]),sa=m(["\n"],["\\n"]),ta=m(["\x00"],["\\u0000"]);function R(a){return Object.isFrozen(a)&&Object.isFrozen(a.raw)}function S(a){return-1===a.toString().indexOf("`")}var ua=S(function(a){return a(ma)})||S(function(a){return a(na)})||S(function(a){return a(oa)})||S(function(a){return a(pa)}),va=R(qa)&&R(ra)&&R(sa)&&R(ta);var wa=[],xa=function(a){var b;if(b=P(Q(),"safevalues").l){a="A URL with content '"+a+"' was sanitized away.";var c;if(c=b)if(c=b&&L){c=L.value;var d=b?ja(P(Q(),b.g())):K;c=c>=d.value}c&&(b=P(Q(),b.g()),"function"===typeof a&&a(),M||(M=new ha),ka(b))}};-1===wa.indexOf(xa)&&wa.push(xa);function ya(a){var b=da.apply(1,arguments);if(!Array.isArray(a)||!Array.isArray(a.raw)||a.length!==a.raw.length||!ua&&a===a.raw||!(ua&&!va||R(a))||b.length+1!==a.length)throw new TypeError("\n    ############################## ERROR ##############################\n\n    It looks like you are trying to call a template tag function (fn`...`)\n    using the normal function syntax (fn(...)), which is not supported.\n\n    The functions in the safevalues library are not designed to be called\n    like normal functions, and doing so invalidates the security guarantees\n    that safevalues provides.\n\n    If you are stuck and not sure how to proceed, please reach out to us\n    instead through:\n     - go/ise-hardening-yaqs (preferred) // LINE-INTERNAL\n     - g/ise-hardening // LINE-INTERNAL\n     - https://github.com/google/safevalues/issues\n\n    ############################## ERROR ##############################");
if(0===b.length)return A(a[0]);var c=a[0].toLowerCase();if(/^data:/.test(c))throw Error("Data URLs cannot have expressions in the template literal input.");if(/^https:\/\//.test(c)||/^\/\//.test(c)){var d=c.indexOf("//")+2;var e=c.indexOf("/",d);if(e<=d)throw Error("Can't interpolate data in a url's origin, Please make sure to fully specify the origin, terminated with '/'.");d=c.substring(d,e);if(!/^[0-9a-z.:-]+$/i.test(d))throw Error("The origin contains unsupported characters.");if(!/^[^:]*(:[0-9]+)?$/i.test(d))throw Error("Invalid port number.");
if(!/(^|\.)[a-z][^.]*$/i.test(d))throw Error("The top-level domain must start with a letter.");d=!0}else d=!1;if(!d)if(/^\//.test(c))if("/"===c||1<c.length&&"/"!==c[1]&&"\\"!==c[1])d=!0;else throw Error("The path start in the url is invalid.");else d=!1;if(!(d=d||RegExp("^[^:\\s\\\\/]+/").test(c)))if(/^about:blank/.test(c)){if("about:blank"!==c&&!/^about:blank#/.test(c))throw Error("The about url is invalid.");d=!0}else d=!1;if(!d)throw Error("Trying to interpolate expressions in an unsupported url format.");
c=a[0];for(d=0;d<b.length;d++)c+=encodeURIComponent(b[d])+a[d+1];return A(c)};var za=l(["//www.gstatic.com/call-tracking/call-tracking_9.js"]),Aa=l(["//www.gstatic.com/call-tracking/call-tracking_7.js"]),Ba=[0],Ca=[835483319,11263478307],Da=ya(za),T=ya(Aa);if(window._googWcmAk){var U=parseInt(window._googWcmAk,10);-1===Ba.indexOf(U)&&(0<=Ca.indexOf(U)||0>U%100)&&(T=Da)}var V=document.createElement("script");V.async=1;var W;
if(T instanceof z&&T.constructor===z)W=T.g;else{var X=typeof T;w("expected object of type TrustedResourceUrl, got '%s' of type %s",T,"object"!=X?X:T?Array.isArray(T)?"array":X:"null");W="type_error:TrustedResourceUrl"}V.src=W;var Ea,Fa,Ga,Y=null==(Ga=(Fa=(V.ownerDocument&&V.ownerDocument.defaultView||window).document).querySelector)?void 0:Ga.call(Fa,"script[nonce]");(Ea=Y?Y.nonce||Y.getAttribute("nonce")||"":"")&&V.setAttribute("nonce",Ea);var Z=document.getElementsByTagName("script")[0];
V.setAttribute("nonce",Z.nonce||Z.getAttribute("nonce"));Z.parentNode.insertBefore(V,Z);}).call(this);
